---
title: "NY NOAA Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

```{r, include=FALSE}
data("ny_noaa")
```

```{r, include=FALSE}
noaa_new = ny_noaa %>% 
  janitor::clean_names() %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  filter(year %in% c("2010")) %>% 
  mutate(tmax = as.numeric(tmax), 
         tmin = as.numeric(tmin),
         tmin = tmin / 10,
         tmax = tmax / 10,
         prcp = prcp / 10) %>% 
  select(-day, -snwd)
```

### Chart A
```{r, message = FALSE}
noaa_new %>% 
  mutate(month = as.factor(month)) %>% 
  plot_ly(y = ~ prcp, color = ~ month, type = "box", colors = "viridis")

```

###Chart B
```{r, message = FALSE}
noaa_new %>% 
  plot_ly(x = ~ tmin, y = ~ tmax, color = ~ month, type = "scatter", mode = "markers")
```

