---
title: "Dashboard for NY NOAA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```


```{r, include=FALSE}
data("ny_noaa")

noaa_new = ny_noaa %>% 
  janitor::clean_names() %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  filter(year %in% c("2010")) %>% 
  mutate(tmax = as.numeric(tmax), 
         tmin = as.numeric(tmin),
         tmin = tmin / 10,
         tmax = tmax / 10,
         prcp = prcp / 10) %>% 
  select(-day, -snwd)

## Only considering the weather data for the year of 2010, and adjusted some variables to make them within reasonable ranges.
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: tmax (°C) vs tmin (°C) in 2010 

```{r, message=FALSE, echo=FALSE}
noaa_new %>% 
  mutate(text_label = as.factor(month)) %>% 
  plot_ly(x = ~ tmin, y = ~ tmax, color = ~ month, type = "scatter", mode = "markers", text = ~ text_label, alpha = 0.5)

## This plot shows that there is a positive relationship between tmin and tmax in 2010: as tmin increases, tmax increases. 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: tmax (°C) trends in 2010 by month

```{r, message=FALSE, echo=FALSE}
noaa_new %>% 
  mutate(month = as.factor(month)) %>% 
  plot_ly(y = ~ tmax, x = ~ month, color = ~ month, text = ~ month, type = "box", colors = "viridis")

## This plot demonstrates the trend of tmax in 2010, we can see that the tmax are higher in summer months and lower in colder months. 
```

### Chart C: number of days with precipitation (mm) at station US1NYAB0001 in August 2010

```{r, message=FALSE, echo=FALSE}
noaa_new %>% 
  drop_na(prcp) %>% 
  filter(id %in% c("US1NYAB0001")) %>% 
  filter(month %in% c("8")) %>%
  count(prcp) %>% 
  mutate(prcp = as.factor(prcp),
         prcp = fct_reorder(prcp, n)) %>% 
  rename(precipitation_mm = prcp, number_of_days = n) %>% 
  plot_ly(x = ~ precipitation_mm, y = ~ number_of_days, color = ~ precipitation_mm, type = "bar", colors = "viridis")

## The barplot here shows the number of days the station "US1NYAB0001" detected precipitation in August 2010. There were 14 days that the station detect 0 mm of precipitation and 2 days with 1.3 mm of precipitation.

## to knit: rmarkdown::render("dashboard_template.Rmd", output_format = "flexdashboard::flex_dashboard")
```

